# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce          # single node can access the volume at a time in a read-write manner.
#   hostPath:                   # node's Localfile system
#     path: /data           #Directory where redis data will be store on node's filesystem.    /data/redis
#     type: FileOrCreate              
#   persistentVolumeReclaimPolicy: Retain    #if pvc deleted then what happen.

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem    #The way that storage is treated .Filesystem is the way the volume is accessed by the container
    # pv will be mounted as a filesystem. allowing the data to be read and written as files
  storageClassName: standard
  accessModes:
    - ReadWriteOnce          # single node can access the volume at a time in a read-write manner.
  hostPath:                   # node's Localfile system
    path: /data/           #Directory where redis data will be store on node's filesystem.    /data/redis
    type: DirectoryOrCreate              
  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  volumeName: redis-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


#Here I am making changes for newBranch changes test.In second time because the first time I did't push newBranch in my code 
#That's why I am making some changes now.
# volumeMode: Block  -> Volume presented to the container as a block device((Raw Storage->Oracle mongoDB)) (own filesyatem on the block storage)